src/Entity/Study/MeasureMetaDataGroup.php
<?php

namespace App\Entity\Study;

use App\Entity\Administration\UuidEntity;
use App\Entity\Constant\ReviewDataDictionary;
use App\Form\MeasureType;
use App\Service\Questionnaire\Questionable;
use App\Service\Review\Reviewable;
use App\Service\Review\ReviewDataCollectable;
use App\Service\Review\ReviewValidator;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;

#[ORM\Table(name: 'experiment_measure')]
#[ORM\Entity]
class MeasureMetaDataGroup extends UuidEntity implements Questionable, Reviewable
{
    /**
     * One basic Information section has One Experiment.
     */
    #[ORM\OneToOne(inversedBy: 'measureMetaDataGroup')]
    protected ?Experiment $experiment = null;

    #[ORM\Column(type: 'json', length: 1500, nullable: true)]
    #[SerializedName('measures')]
    #[Groups(['study'])]
    private ?array $measures = null;

    #[ORM\Column(type: 'json', length: 1500, nullable: true)]
    #[SerializedName('apparatus')]
    #[Groups(['study'])]
    private ?array $apparatus = null;

    public function getReviewCollection(): array
    {
        return [
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::MEASURES,
                $this->getMeasures(),
                ReviewValidator::validateArrayValues($this->getMeasures())
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::APPARATUS,
                $this->getApparatus(),
                ReviewValidator::validateArrayValues($this->getApparatus())
            ),
        ];
    }

    public function getFormTypeForEntity(): string
    {
        return MeasureType::class;
    }

    public function getMeasures(): ?array
    {
        return $this->measures;
    }

    public function setMeasures(?array $measures): void
    {
        $this->measures = $measures == null ? null : array_values($measures);
    }

    public function getApparatus(): ?array
    {
        return $this->apparatus;
    }

    public function setApparatus(?array $apparatus): void
    {
        $this->apparatus = $apparatus == null ? null : array_values($apparatus);
    }

    public function getExperiment(): Experiment
    {
        return $this->experiment;
    }

    public function setExperiment(Experiment $experiment): void
    {
        $this->experiment = $experiment;
    }
}

src/Entity/Study/MethodMetaDataGroup.php
<?php

namespace App\Entity\Study;

use App\Entity\Administration\UuidEntity;
use App\Entity\Constant\ReviewDataDictionary;
use App\Form\MethodType;
use App\Service\Questionnaire\Questionable;
use App\Service\Review\Reviewable;
use App\Service\Review\ReviewDataCollectable;
use App\Service\Review\ReviewValidator;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;

#[ORM\Table(name: 'experiment_method')]
#[ORM\Entity]
class MethodMetaDataGroup extends UuidEntity implements Questionable, Reviewable
{
    /**
     * One basic Information section has One Experiment.
     */
    #[ORM\OneToOne(inversedBy: 'methodMetaDataGroup')]
    protected ?Experiment $experiment = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('research_design')]
    #[Groups(['study'])]
    private ?string $research_design = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('experimental_details')]
    #[Groups(['experimental'])]
    private ?string $experimental_details = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('non_experimental_details')]
    #[Groups(['non_experimental'])]
    private ?string $non_experimental_details = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('observational_type')]
    #[Groups(['non_experimental'])]
    private ?string $observational_type = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('setting')]
    #[Groups(['study'])]
    private ?string $setting = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('setting_location')]
    #[Groups(['study'])]
    private ?string $setting_location = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('manipulations')]
    #[Groups(['experimental'])]
    private ?string $manipulations = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('experimental_design')]
    #[Groups(['experimental'])]
    private ?string $experimental_design = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('control_operations')]
    #[Groups(['experimental'])]
    private ?string $control_operations = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('other_control_operations')]
    #[Groups(['experimental'])]
    private ?string $other_control_operations = null;

    public function getReviewCollection(): array
    {
        return [
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::DESIGN,
                [$this->getResearchDesign()],
                ReviewValidator::validateSingleValue($this->getResearchDesign())
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::EXPERIMENTAL,
                [$this->getExperimentalDetails()],
                ReviewValidator::validateSingleValue($this->getExperimentalDetails()),
                $this->getResearchDesign() === 'Experimental'
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::NON_EXPERIMENTAL,
                [$this->getNonExperimentalDetails()],
                ReviewValidator::validateSingleValue($this->getNonExperimentalDetails()),
                $this->getResearchDesign() === 'Non-experimental'
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::OBSERVABLE_TYPE,
                [$this->getObservationalType()],
                ReviewValidator::validateSingleValue($this->getObservationalType()),
                $this->getResearchDesign() === 'Non-experimental' && $this->getNonExperimentalDetails() === 'Observational study'
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::SETTING,
                [$this->getSetting()],
                ReviewValidator::validateSingleValue($this->getSetting())
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::SETTING_LOCATION,
                [$this->getSettingLocation()],
                ReviewValidator::validateSingleValue($this->getSettingLocation()),
                $this->getSetting() === 'Real-life setting' || $this->getSetting() === 'Natural setting'
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::MANIPULATIONS,
                [$this->getManipulations()],
                ReviewValidator::validateSingleValue($this->getManipulations()),
                $this->getResearchDesign() === 'Experimental'
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::EXPERIMENTAL_DESIGN,
                [$this->getExperimentalDesign()],
                ReviewValidator::validateSingleValue($this->getExperimentalDesign()),
                $this->getResearchDesign() === 'Experimental'
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::CONTROL_OPS,
                [$this->getControlOperations() !== 'Other' ? $this->getControlOperations() : $this->getOtherControlOperations()],
                ($this->getControlOperations() !== 'Other' && ReviewValidator::validateSingleValue($this->getControlOperations()))
                || ($this->getControlOperations() === 'Other' && ReviewValidator::validateSingleValue($this->getOtherControlOperations())),
                $this->getResearchDesign() === 'Experimental'
            ),
        ];
    }

    public function getFormTypeForEntity(): string
    {
        return MethodType::class;
    }

    public function getSetting(): ?string
    {
        return $this->setting;
    }

    public function setSetting(?string $setting): void
    {
        $this->setting = $setting;
    }

    public function getSettingLocation(): ?string
    {
        return $this->setting_location;
    }

    public function setSettingLocation(?string $setting_location): void
    {
        $this->setting_location = $setting_location;
    }

    public function getResearchDesign(): ?string
    {
        return $this->research_design;
    }

    public function setResearchDesign(?string $research_design): void
    {
        $this->research_design = $research_design;
    }

    public function getExperimentalDetails(): ?string
    {
        return $this->experimental_details;
    }

    public function setExperimentalDetails(?string $experimental_details): void
    {
        $this->experimental_details = $experimental_details;
    }

    public function getNonExperimentalDetails(): ?string
    {
        return $this->non_experimental_details;
    }

    public function setNonExperimentalDetails(?string $non_experimental_details): void
    {
        $this->non_experimental_details = $non_experimental_details;
    }

    public function getObservationalType(): ?string
    {
        return $this->observational_type;
    }

    public function setObservationalType(?string $observational_type): void
    {
        $this->observational_type = $observational_type;
    }

    public function getManipulations(): ?string
    {
        return $this->manipulations;
    }

    public function setManipulations(?string $manipulations): void
    {
        $this->manipulations = $manipulations;
    }

    public function getExperimentalDesign(): ?string
    {
        return $this->experimental_design;
    }

    public function setExperimentalDesign(?string $experimental_design): void
    {
        $this->experimental_design = $experimental_design;
    }

    public function getControlOperations(): ?string
    {
        return $this->control_operations;
    }

    public function setControlOperations(?string $control_operations): void
    {
        $this->control_operations = $control_operations;
    }

    public function getOtherControlOperations(): ?string
    {
        return $this->other_control_operations;
    }

    public function setOtherControlOperations(?string $other_control_operations): void
    {
        $this->other_control_operations = $other_control_operations;
    }

    public function getExperiment(): Experiment
    {
        return $this->experiment;
    }

    public function setExperiment(Experiment $experiment): void
    {
        $this->experiment = $experiment;
    }
}

src/Entity/Study/SampleMetaDataGroup.php
<?php

namespace App\Entity\Study;

use App\Entity\Administration\UuidEntity;
use App\Entity\Constant\ReviewDataDictionary;
use App\Form\SampleType;
use App\Service\Questionnaire\Questionable;
use App\Service\Review\Reviewable;
use App\Service\Review\ReviewDataCollectable;
use App\Service\Review\ReviewValidator;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;

#[ORM\Table(name: 'experiment_sample')]
#[ORM\Entity]
class SampleMetaDataGroup extends UuidEntity implements Questionable, Reviewable
{
    /**
     * One Sample section has One Experiment.
     */
    #[ORM\OneToOne(inversedBy: 'sampleMetaDataGroup')]
    protected ?Experiment $experiment = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('participants')]
    #[Groups(['study'])]
    private ?string $participants = null;

    #[ORM\Column(type: 'json', length: 1500, nullable: true)]
    #[SerializedName('inclusion_criteria')]
    #[Groups(['study'])]
    private ?array $inclusion_criteria = null;

    #[ORM\Column(type: 'json', length: 1500, nullable: true)]
    #[SerializedName('exclusion_criteria')]
    #[Groups(['study'])]
    private ?array $exclusion_criteria = null;

    #[ORM\Column(type: 'json', length: 1500, nullable: true)]
    #[SerializedName('population')]
    #[Groups(['study'])]
    private ?array $population = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('sampling_method')]
    #[Groups(['study'])]
    private ?string $sampling_method = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('other_sampling_method')]
    #[Groups(['study'])]
    private ?string $other_sampling_method = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('sample_size')]
    #[Groups(['study'])]
    private ?string $sample_size = null;

    #[ORM\Column(type: 'text', length: 1500, nullable: true)]
    #[SerializedName('power_analysis')]
    #[Groups(['study'])]
    private ?string $power_analysis = null;

    public function getReviewCollection(): array
    {
        return [
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::PARTICIPANTS,
                [$this->getParticipants()],
                ReviewValidator::validateSingleValue($this->getParticipants())
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::POPULATION,
                $this->getPopulation(),
                ReviewValidator::validateArrayValues($this->getPopulation())
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::INCLUSION,
                $this->getInclusionCriteria(),
                ReviewValidator::validateArrayValues($this->getInclusionCriteria())
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::EXCLUSION,
                $this->getExclusionCriteria(),
                ReviewValidator::validateArrayValues($this->getExclusionCriteria())
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::SAMPLING,
                [$this->getSamplingMethod() !== 'Other' ? $this->getSamplingMethod() : $this->getOtherSamplingMethod()],
                ($this->getSamplingMethod() !== 'Other' && ReviewValidator::validateSingleValue($this->getSamplingMethod()))
                || ($this->getSamplingMethod() === 'Other' && ReviewValidator::validateSingleValue($this->getOtherSamplingMethod()))
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::SAMPLE_SIZE,
                [$this->getSampleSize()],
                ReviewValidator::validateSingleValue($this->getSampleSize())
            ),
            ReviewDataCollectable::createFrom(
                ReviewDataDictionary::POWER_ANALYSIS,
                [$this->getPowerAnalysis()],
                ReviewValidator::validateSingleValue($this->getPowerAnalysis())
            ),
        ];
    }

    public function getFormTypeForEntity(): string
    {
        return SampleType::class;
    }

    public function getParticipants(): ?string
    {
        return $this->participants;
    }

    public function setParticipants(?string $participants): void
    {
        $this->participants = $participants;
    }

    public function getInclusionCriteria(): ?array
    {
        return $this->inclusion_criteria;
    }

    public function setInclusionCriteria(?array $inclusion_criteria): void
    {
        $this->inclusion_criteria = $inclusion_criteria == null ? null : array_values($inclusion_criteria);
    }

    public function getExclusionCriteria(): ?array
    {
        return $this->exclusion_criteria;
    }

    public function setExclusionCriteria(?array $exclusion_criteria): void
    {
        $this->exclusion_criteria = $exclusion_criteria == null ? null : array_values($exclusion_criteria);
    }

    public function getPopulation(): ?array
    {
        return $this->population;
    }

    public function setPopulation(?array $population): void
    {
        $this->population = $population == null ? null : array_values($population);
    }

    public function getSamplingMethod(): ?string
    {
        return $this->sampling_method;
    }

    public function setSamplingMethod(?string $sampling_method): void
    {
        $this->sampling_method = $sampling_method;
    }

    public function getOtherSamplingMethod(): ?string
    {
        return $this->other_sampling_method;
    }

    public function setOtherSamplingMethod(?string $other_sampling_method): void
    {
        $this->other_sampling_method = $other_sampling_method;
    }

    public function getSampleSize(): ?string
    {
        return $this->sample_size;
    }

    public function setSampleSize(?string $sample_size): void
    {
        $this->sample_size = $sample_size;
    }

    public function getPowerAnalysis(): ?string
    {
        return $this->power_analysis;
    }

    public function setPowerAnalysis(?string $power_analysis): void
    {
        $this->power_analysis = $power_analysis;
    }

    public function getExperiment(): Experiment
    {
        return $this->experiment;
    }

    public function setExperiment(Experiment $experiment): void
    {
        $this->experiment = $experiment;
    }
}

templates/pages/study/datasets.html.twig
{% extends "layouts/threeColumn.html.twig" %}
{% from "components/_macros.html.twig" import helpButton %}
{% from "components/_macros.html.twig" import sectionHelp %}
{% from "components/_macros.html.twig" import formHelp %}
{% from "components/_macros.html.twig" import dropzoneTemplate %}
{% from "components/_fileDisplayCard.html.twig" import fileDisplayCard %}

{% set isPartOfStudyDocumentation = true %}

{% block title %}
    {{ "title.dataset.title"|trans }}
{% endblock %}

{% block content %}
    <h2 class="MetaDataGroup-Title">
        {{ "title.dataset.title"|trans }}
    </h2>
    {{ include("components/_infoBridge.html.twig",{value: experiment.id}) }}
    <div class="mt-6">
        <form action="{{ oneup_uploader_endpoint("datasets") }}" data-experiment-id="{{ experiment.id }}"
              class="mx-6 border-2 !border-dashed border-mono-500 dropzone" id="datawiz-dropzone"
              data-preview-csv="{{ path("File-preview-csv",{"id": " "}) }}"
              data-submit-csv="{{ path("File-submit-csv",{"id": " "}) }}"
              data-preview-sav="{{ path("File-preview-sav",{"id": " "}) }}"
              data-submit-sav="{{ path("File-submit-sav",{"id": " "}) }}"
        >
            {{ dropzoneTemplate() }}
            <input type="hidden" id="dataset-import-data" name="dataset-import-data" value=""/>
        </form>
    </div>
    <div class="mt-6 MetaData-Title">
        <legend class="MetaData-Legend">
            {{ "title.dataset.h3"|trans }}
        </legend>
        {{ helpButton("my_datasets") }}
    </div>
    {% if experiment.originalDatasets|length > 0 %}
        <ul class="mx-6">
            {% for dataset in experiment.originalDatasets %}
                    {{ fileDisplayCard(dataset, 'dataset', loop.index) }}
            {% endfor %}
        </ul>
    {% else %}
        <p class="mx-6">
            {{ "title.dataset.empty"|trans }}
        </p>
    {% endif %}

    <!-- Modal for importing a dataset -->
    {{ include('pages/study/_datasetImportModal.html.twig') }}

    {{ render(controller('App\\Controller\\NavigationController::savebarNavigation', {
        request: app.request,
        prevUrl: 'Study-sample',
        prevTitle: 'title.samples.title'|trans,
        nextUrl: 'Study-materials',
        nextTitle: 'title.material.title-short'|trans,
        form: null
    })) }}
{% endblock %}

{% block help_for_section %}
    {{ sectionHelp("datasets") }}
{% endblock %}

{% block help_for_metadata %}
    {{ formHelp("datasets", "my_datasets", "title.dataset.h3") }}
{% endblock %}

templates/pages/study/method.html.twig
{% extends "layouts/threeColumn.html.twig" %}
{% from "components/_macros.html.twig" import helpButton %}
{% from "components/_macros.html.twig" import sectionHelp %}
{% from "components/_macros.html.twig" import formHelp %}

{% set isPartOfStudyDocumentation = true %}
{% set isStudyDescriptionSubItem = true %}

{% block title %}
    {{ "title.method.title"|trans }}
{% endblock %}

{% block content %}
    <h2 class="MetaDataGroup-Title">
        {{ "title.method.title"|trans }}
    </h2>

    {{ form_start(form) }}
    {{ form_errors(form) }}

    <fieldset>
        <div class="MetaData-Title">
            <legend class="MetaData-Legend" id="{{ 'input.design.legend'|trans|slug }}">
                {{ "input.design.legend"|trans }}
            </legend>
            {{ helpButton("research_design") }}
        </div>
        {{ form_label(form.research_design) }}
        <div class="MetaData-Widget" x-data=""
             x-init="$store.app.researchDesign = '{{ form.research_design.vars.value }}'">
            {{ form_errors(form.research_design) }}
            {%- for choice in form.research_design %}
                {{ form_widget(choice) }}
                {{ form_label(choice, null, {
                    'label_attr': {
                        'class': 'RadioButton-Label RadioButton-Label_card',
                        '@click': '$store.app.researchDesign = "' ~ choice.vars.value ~ '"'
                    },
                    'label_html': true,
                }) }}
            {% endfor -%}
            <span id="{{ 'input.design.details.legend'|trans|slug }}"></span>
            <div x-show="$store.app.researchDesign === '{{ form.research_design.vars.choices[0].value }}'"
                 x-cloak="x-cloak" class="mt-4 ml-4" x-transition:enter="transition duration-300"
                 x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100"
                 x-transition:leave="transition duration-[0ms]" x-transition:leave-start="opacity-100"
                 x-transition:leave-end="opacity-0">
                {{ form_label(form.experimentalDetails) }}
                {{ form_errors(form.experimentalDetails) }}
                {%- for choice in form.experimentalDetails %}
                    {{ form_widget(choice) }}
                    {{ form_label(choice, null, {
                        'label_attr': {'class': 'RadioButton-Label'},
                        'label_html': true,
                    }) }}
                {% endfor -%}
            </div>
            <div x-show="$store.app.researchDesign === '{{ form.research_design.vars.choices[1].value }}'"
                 x-cloak="x-cloak" class="mt-4 ml-4"
                 x-init="$store.app.nonExperimentalType = '{{ form.nonExperimentalDetails.vars.value }}'"
                 x-transition:enter="transition duration-300" x-transition:enter-start="opacity-0"
                 x-transition:enter-end="opacity-100" x-transition:leave="transition duration-[0ms]"
                 x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0">

                {{ form_label(form.nonExperimentalDetails) }}
                {{ form_errors(form.nonExperimentalDetails) }}
                {%- for choice in form.nonExperimentalDetails %}
                    {{ form_widget(choice) }}

                    {{ form_label(choice, null, {
                        "label_attr":           {
                            'class': 'RadioButton-Label',
                            '@click': '$store.app.nonExperimentalType = "' ~ choice.vars.value ~ '"',
                        },
                        'label_html': true,
                    }) }}

                    {% if choice.vars.value == 'Observational study' %}
                        {{- form_label(form.observationalType, null, {
                            'label_attr': {
                                'class': 'ml-[1.375rem] mt-1 block',
                            }
                        }) -}}
                        {{- form_errors(form.observationalType) -}}
                        {{- form_widget(form.observationalType, {
                            'attr': {
                                'class': 'ml-[1.375rem] disabled:opacity-50 p-1 mt-1 block',
                                'x-data': '',
                                'x-bind:disabled': '$store.app.nonExperimentalType !== "' ~ choice.vars.value ~ '"'
                            }
                        }) -}}
                    {% endif %}
                {% endfor -%}
            </div>
        </div>
    </fieldset>

    <fieldset class="mt-8">
        <div class="MetaData-Title">
            <legend class="MetaData-Legend" id="{{ 'input.setting.legend'|trans|slug }}">
                {{ "input.setting.legend"|trans }}
            </legend>
            {{ helpButton("setting") }}
        </div>
        {{ form_label(form.setting) }}
        <div x-data="" class="MetaData-Widget" x-init="$store.app.settingType = '{{ form.setting.vars.value }}'">
            {{ form_errors(form.setting) }}
            {%- for choice in form.setting %}
                {{ form_widget(choice) }}
                {{ form_label(choice, null, {
                    'label_attr': {
                        'class': 'RadioButton-Label',
                        '@click': '$store.app.settingType = "' ~ choice.vars.value ~ '"'
                    },
                    'label_html': true,
                }) }}
            {% endfor -%}
        </div>
        {{ form_label(form.settingLocation, null, {
            'label_attr': {'id': 'input.setting.location.legend'|trans|slug },
        }) }}
        <div class="MetaData-Widget">
            {{ form_errors(form.settingLocation) }}
            {{ form_widget(form.settingLocation) }}
        </div>
    </fieldset>

    <fieldset class="mt-8" x-data=""
              x-show="$store.app.researchDesign === '{{ form.research_design.vars.choices[0].value }}'"
              x-cloak="x-cloak">
        <div class="MetaData-Title">
            <legend class="MetaData-Legend" id="{{ 'input.manipulations.legend'|trans|slug }}">
                {{ "input.manipulations.legend"|trans }}
            </legend>
            {{ helpButton("manipulations") }}
        </div>
        {{ form_label(form.manipulations) }}
        <div class="MetaData-Widget">
            {{ form_errors(form.manipulations) }}
            {{ form_widget(form.manipulations) }}
        </div>
    </fieldset>

    <fieldset class="mt-8" x-data=""
              x-show="$store.app.researchDesign === '{{ form.research_design.vars.choices[0].value }}'"
              x-cloak="x-cloak">
        <div class="MetaData-Title">
            <legend class="MetaData-Legend" id="{{ 'input.experimental-design.legend'|trans|slug }}">
                {{ "input.experimental-design.legend"|trans }}
            </legend>
            {{ helpButton("experimental_design") }}
        </div>
        {{ form_label(form.experimental_design, null, {
            'label_attr': {'class': 'MetaData-Label'},
        }) }}
        <div class="MetaData-Widget">
            {{ form_errors(form.experimental_design) }}
            {%- for choice in form.experimental_design %}
                {{ form_widget(choice, {
                    'attr': {'class': 'RadioButton-Input'}
                }) }}
                {{ form_label(choice, null, {
                    'label_attr': {'class': 'RadioButton-Label'},
                    'label_html': true,
                    'class': 'RadioButton-Input'
                }) }}
            {% endfor -%}
        </div>
    </fieldset>

    <fieldset class="mt-8" x-data="" x-init="$store.app.controlOperations = '{{ form.control_operations.vars.value }}'"
              x-show="$store.app.researchDesign === '{{ form.research_design.vars.choices[0].value }}'"
              x-cloak="x-cloak">
        <div class="MetaData-Title">
            <legend class="MetaData-Legend" id="{{ 'input.control-operations.legend'|trans|slug }}">
                {{ "input.control-operations.legend"|trans }}
            </legend>
            {{ helpButton("control_operations") }}
        </div>
        {{ form_label(form.control_operations) }}
        <div class="MetaData-Widget">
            {{ form_errors(form.control_operations) }}
            {%- for choice in form.control_operations %}
                {{ form_widget(choice) }}
                {{ form_label(choice, null, {
                    'label_attr': {
                        'class': 'RadioButton-Label',
                        '@click': '$store.app.controlOperations = "' ~ choice.vars.value ~ '"'
                    }
                }) }}
            {% endfor -%}
        </div>
        {{ form_label(form.otherControlOperations, null, {
            'label_attr': {
                'class': 'MetaData-Label ml-[1.375rem]',
            }
        }) }}
        <div class="flex MetaData-Widget">
            {{ form_errors(form.otherControlOperations) }}
            {{ form_widget(form.otherControlOperations, {
                'attr': {
                    'class': 'MetaData-TextInput disabled:opacity-50 ml-[1.375rem]',
                    'x-bind:disabled': '$store.app.controlOperations !== `Other`'
                }
            }) }}
        </div>
    </fieldset>

    {{ render(controller('App\\Controller\\NavigationController::savebarNavigation', {
        request: app.request,
        prevTitle: 'title.theroies.title',
        nextTitle: 'title.measures.title',
        form: form
    })) }}

    {{ form_end(form) }}
{% endblock %}

{% block help_for_section %}
    {{ sectionHelp("method") }}
{% endblock %}

{% block help_for_metadata %}
    {{ formHelp("method", "research_design", "input.design.legend") }}
    {{ formHelp("method", "setting", "input.setting.legend") }}
    {{ formHelp("method", "manipulations", "input.manipulations.legend") }}
    {{ formHelp("method", "experimental_design", "input.experimental-design.legend") }}
    {{ formHelp("method", "control_operations", "input.control-operations.legend") }}
{% endblock %}